In [1]:
import torch

In [2]:
from hexconvolution import NoMCTSModel
from hexboard import Board
from hexgame import MultiHexGame

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
models = (NoMCTSModel(board_size=3, layers=1),)
boards = [Board(size=3) for idx in range(3)]

In [4]:
multihexgame = MultiHexGame(boards, models, device, noise=None, noise_parameters=None, temperature=0.1)

In [5]:
board_states, moves, targets = multihexgame.play_moves()

In [6]:
multihexgame

Board
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1. -1. -1.]]
Made moves
{(1, 2), (0, 1), (0, 0), (0, 2), (2, 1), (2, 0), (2, 2), (1, 0), (1, 1)}
Legal moves
set()
Winner
[0]
Connected sets
[[({(0, 1), (2, 0), (0, 0), (1, 0), (1, 1)}, {0, 1, 2})], [({(1, 2), (0, 2), (2, 1), (2, 2)}, {1, 2})]]
Board
[[ 0.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  0. -1.]]
Made moves
{(1, 2), (0, 1), (2, 0), (1, 1), (2, 2), (1, 0), (0, 2)}
Legal moves
set()
Winner
[0]
Connected sets
[[({(0, 1), (2, 0), (1, 0), (1, 1)}, {0, 1, 2})], [({(1, 2), (0, 2), (2, 2)}, {2})]]
Board
[[-1.  1.  0.]
 [-1. -1. -1.]
 [ 1.  1.  1.]]
Made moves
{(0, 1), (1, 2), (0, 0), (2, 1), (2, 0), (2, 2), (1, 0), (1, 1)}
Legal moves
set()
Winner
[1]
Connected sets
[[({(0, 1)}, {0}), ({(2, 0), (2, 1), (2, 2)}, {2})], [({(1, 2), (1, 0), (0, 0), (1, 1)}, {0, 1, 2})]]

In [7]:
targets

tensor([1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
        1., 1., 0., 0., 1., 1.])