In [311]:
import torch
from torch.distributions.dirichlet import Dirichlet

In [312]:
from hexconvolution import NoMCTSModel
from hexboard import Board
from hexgame import HexGame

In [313]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [314]:
noise = Dirichlet(torch.full((121,),0.03))
model = NoMCTSModel(board_size=11, layers=5, input_channels=2, noise=noise, noise_level=0.25)

In [315]:
board = Board(size=11)

In [316]:
board

Board
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Legal moves
{(7, 3), (6, 9), (0, 7), (1, 6), (0, 10), (3, 7), (2, 5), (8, 5), (5, 8), (4, 0), (10, 8), (9, 0), (6, 7), (5, 5), (10, 7), (7, 6), (6, 10), (0, 4), (1, 1), (4, 10), (3, 2), (2, 6), (8, 2), (4, 5), (9, 3), (6, 0), (7, 5), (0, 1), (3, 1), (9, 9), (7, 8), (2, 1), (8, 9), (9, 4), (5, 1), (10, 3), (7, 2), (1, 5), (3, 6), (2, 2), (1, 10), (8, 6), (4, 1), (10, 9), (9, 7), (6, 4), (5, 4), (10, 4), (7, 1), (0, 5), (1, 0), (0, 8), (3, 5), (2, 7), (8, 3), (5, 10), (4, 6), (10, 10), (9, 2), (6, 1), (5, 7), (7, 4), (0, 2), (1, 3), (4, 8), (3, 0), (2, 8), (9, 8), (8, 0), (6, 2), (3, 10), (8,

In [317]:
hexgame = HexGame(board, model, device)

In [318]:
board_states, moves, targets = hexgame.play_moves()

In [319]:
hexgame

Board
[[-1.  1. -1. -1. -1. -1.  0.  0.  1.  1.  1.]
 [-1. -1.  1. -1. -1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1. -1.  1. -1. -1.  1.  1. -1. -1.  0.]
 [-1. -1.  1. -1.  1.  1.  1.  1.  1.  0. -1.]
 [-1. -1.  1. -1. -1. -1.  1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1. -1. -1. -1.  1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.  0.  1.  1. -1. -1.]
 [ 1. -1. -1.  1.  1.  1. -1.  1. -1.  1.  1.]
 [-1. -1.  1. -1.  1.  1.  1.  1. -1. -1.  1.]
 [ 1. -1.  1.  1. -1. -1.  1. -1.  1. -1. -1.]
 [ 0. -1. -1.  1.  1.  0.  1.  1.  1.  1.  0.]]
Legal moves
{(0, 7), (10, 10), (10, 0), (3, 9), (10, 5), (0, 6), (6, 6), (2, 10)}
Illegal moves
{(7, 3), (6, 9), (1, 6), (0, 10), (3, 7), (2, 5), (8, 5), (5, 8), (4, 0), (10, 8), (9, 0), (6, 7), (5, 5), (10, 7), (7, 6), (6, 10), (0, 4), (1, 1), (4, 10), (3, 2), (2, 6), (8, 2), (4, 5), (9, 3), (6, 0), (7, 5), (0, 1), (3, 1), (9, 9), (7, 8), (2, 1), (8, 9), (9, 4), (5, 1), (10, 3), (7, 2), (1, 5), (3, 6), (2, 2), (1, 10), (8, 6), (4, 1), (10, 9), (9, 7), (6, 4), (5, 4), (10

In [320]:
board_states

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
        